src/Entity/Properties.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertiesRepository")
 *  * @UniqueEntity("title")
 */
class Properties
{

    const HEAT = [
        0 => 'Électrique',
        1 => 'Gaz'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\Length(min=5, max=255)
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(
     *     min = 10,
     *     max = 400
     * )
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^\d{5}/")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    // On on construit une nouvelle propriété on initialise notre datetime
    public function __construct()
    {
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function getFormatedPrice(): string
    {
        return number_format ($this->price, 0, '', ' ');
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatType(): string
    {
        return  self::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Properties;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat' ,ChoiceType::class, [
                'choices' => $this->getChoices(),
                'placeholder' => 'Choisir un mode de chauffage'
            ])
            ->add('city')
            ->add('adress')
            ->add('postal_code')
            ->add('sold')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Properties::class,
            // On traduit le texte en anglais via le fichier translations/forms.fr.yaml
            'translation_domain' => 'forms'
        ]);
    }

    private function getChoices()
    {
        $choices = Properties::HEAT;
        $output = [];
        foreach ($choices as $k => $v){
            $output[$v] = $k;
        }
        return $output;
    }
}

src/Controller/PropertyController.php
<?php 

namespace App\Controller;

use App\Entity\Properties;
use App\Repository\PropertiesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class PropertyController extends AbstractController
{

    // On récupère notre enregistrement par injection dans le construteur

    /**
     * @var PropertiesRepositoy
     */
    private $repository;
    /**
     * @var EntityManagerInterface
     */
    private $em;
    
    public function __construct(PropertiesRepository $repository, EntityManagerInterface $em)
    {
        $this->repository = $repository;
        $this->em = $em;
    
    }

    // On paramètre notre vue

    /**
     * @Route ("/biens", name="property.index")
     * @return Response
     */

    public function index(): Response
    {
        // Récupération de l'enregistrement via find(), findAll(),findOneBy() qui prend un tableau de critère (exemple = findOneby(['floor' => 3])) ou en appelant une méthode du Repository
        // $property = $this->repository->findAllVisible();
        // $property[0]->setSold(true);
        // $this->em->flush();

        // // On cré une nouvelle entité
        // $property = new Properties();
        // $property->setTitle('Mon premier bien')
        //     ->setPrice(200000)
        //     ->setRooms(4)
        //     ->setBedrooms(3)
        //     ->setDescription("Ma petite annonce")
        //     ->setSurface(60)
        //     ->setFloor(3)
        //     ->setHeat(1)
        //     ->setCity('Muret')
        //     ->setAdress('10 Avenue Jacques Douzans')
        //     ->setPostalCode('31600');
        // // Pour envoyer notre entité dans la bdd on a besoin d'un entityManager
        // $em = $this->getDoctrine()->getManager();
        // // On persiste notre entité
        // $em->persist($property);
        // // On porte tous les changements fait dans l'entityManager dans la bdd
        // $em->flush();
        $properties = $this->repository->findAll();
        return $this->render('property/index.html.twig', [
            'current_menu' => 'properties',
            'properties' =>$properties,
            ]);
    }

    /**
     * @Route ("/biens/{slug}-{id}", name="property.show", requirements={"slug": "[a-z0-9\-]*"})
     * @param Properties $property
     * @param string $slug
     * @return Response
     */

    public function show(Properties $property, string $slug): Response
    {
        if ($property->getSlug() !== $slug){ // On vérifie si le slug correspond...
            // Si ce n'est pas le cas on redirige vers la route
            return $this->redirectToRoute('property.show', [
                'id' =>$property->getId(),
                'slug'=>$property->getSlug(),
                ], 301);
        }
        return $this->render('property/show.html.twig', [
            'property' => $property, 
        ]);
    }
}

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tous nos biens{% endblock %}

{% block body %}
<div class="jumbotron text-center">
    <div class="container">
        <h1>Voir tous nos biens</h1>
    </div>
</div>
    <div class="container">
        <div class="row flex">
            {% for property in properties %}
                <div class="col-3">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">
                                <a href="{{ path('property.show', {id :property.id, slug: property.slug})}}">{{ property.title }}</a>
                            </h5>
                            <p class="card-text">{{ property.city }} ({{ property.postalCode }})</p>
                            <div class="text-danger" style="font-size: 2rem; font-weight: bold;">{{ property.getFormatedPrice}} €</div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title property.title %}


{% block body %}
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <h1>{{ property.title }}</h1>
                    <h2>{{ property.rooms }} pièces . {{ property.surface }} m2</h2>
                    <div class="text-primary " style="font-size: 2rem; font-weight: bold;">{{ property.getFormatedPrice }} €</div>
                    <a href="#" class="btn btn-primary">Contacter l'agence</a>
                </div>
                <div class="col-md-8"></div>
            </div>
        </div>
    </div>
    <div class="container mt-4">
        <p>
            {{ property.description | nl2br }}
        </p>
        <div class="row">
            <div class="col-md-8">
                <h2>Caractéristiques</h2>
                <table class="table table-striped">
                    <tr>
                        <td>Surface habitable</td>
                        <td>{{ property.surface }} m2</td>
                    </tr>
                    <tr>
                        <td>Pièces</td>
                        <td>{{ property.rooms }}</td>
                    </tr>
                    <tr>
                        <td>Chambres</td>
                        <td>{{ property.bedrooms }}</td>
                    </tr>
                    <tr>
                        <td>Étages</td>
                        <td>{{ property.floor }}</td>
                    </tr>
                    <tr>
                        <td>Chauffage</td>
                        <td>{{ property.heatType }}</td>
                    </tr>
                </table>
            </div>
            <div class="col-md-4">
                <h2>Spécificités</h2>
            </div>
        </div>
    </div>
{% endblock %}